[PK-207] Refactoring JavaDoc for Celesta
CourseOrchestra/celesta pull request #136
Opened 2018-12-26 21:29 UTC by packpaul

JDOC: documenting and RU->EN in celesta-sql module

2019-01-02 22:41 UTC, inponomarev requested changes
1. Please fetch `dev` branch+ rebase + force push your branch, in order to get the freshest state.
2. Please find in .java-files and correct the following misspelled words:

- adresses
- belog
- commited
- cortage
- Delets
- it'is
- Naitive
- parametrized

2019-01-03 06:38 UTC, packpaul commented
@inponomarev Misspellings fixed.

2019-01-03 07:23 UTC, inponomarev requested changes

2019-01-03 07:23 UTC, inponomarev commented on celesta-sql/src/test/java/ru/curs/celesta/score/ScoreTest.java
> +                new View(g1p, "testit", "select postalcode, city from addresses where flat = 5"))
Cool, but you should have also changed the table name in `celesta-sql\src\test\resources\scores\compositeScore\score\grain1\_grain1.sql`. Tests are now failing because the table with such name is not found )))

2019-01-03 09:01 UTC, inponomarev approved these changes

2019-01-03 09:02 UTC, merged