user guide update
CourseOrchestra/celesta pull request #143
Opened 2019-03-14 16:02 UTC by inponomarev

## Overview

Edited User Guide in order to remove outdated information and to catch up with recent changes.

---

### Checklist

- [ ] Change is covered by automated tests.
- [ ] JavaDoc is provided for all new/changed public APIs.
- [ ] User Guide is updated.
- [ ] CI builds pass.

2019-03-14 17:37 UTC, packpaul requested changes

2019-03-14 17:37 UTC, packpaul commented on celesta-documentation/src/main/asciidoc/0000_Celesta.adoc
>  include::1012_maven_dependencies.adoc[leveloffset=+2, tag="maven_dependencies"]
Why not `1012_demonstration.adoc`?

2019-03-14 17:37 UTC, packpaul commented on celesta-documentation/src/main/asciidoc/1013_maven_plugin.adoc
> +Эти файлы используются для во время выполнения Celesta для того, чтобы найти пути ко всем CelestaSQL-файлам внутри jar-файлов на classpath.
"используются для во" -> "используются во"

2019-03-14 23:40 UTC, inponomarev commented on celesta-documentation/src/main/asciidoc/0000_Celesta.adoc
>  include::1012_maven_dependencies.adoc[leveloffset=+2, tag="maven_dependencies"]
fixed

2019-03-14 23:40 UTC, inponomarev commented on celesta-documentation/src/main/asciidoc/1013_maven_plugin.adoc
> +Эти файлы используются для во время выполнения Celesta для того, чтобы найти пути ко всем CelestaSQL-файлам внутри jar-файлов на classpath.
fixed

2019-03-15 10:14 UTC, packpaul approved these changes

2019-03-15 10:14 UTC, merged